apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
      initContainers:
        - name: init
          image: busybox
          command:  ['sh', '-c', 'until nslookup nginx; do echo waiting for nginx; sleep 2; done;']
