
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  # namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnginx
  template:
    metadata:
      labels:
        app: webnginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: vol
      volumes:
      - name: vol
        configMap:
          name: mymap

