apiVersion: v1
kind: Service
metadata:
  name: nginx
  # namespace: ingress-nginx
spec:
  selector:
    app: webnginx
  ports:
    - name: {{ .Values.image.repository }}
      protocol: TCP
      port: {{ .Values.service.port }} #9001
      targetPort: {{ .Values.service.targetport }} #80