apiVersion: v1
kind: Pod
metadata:
  name: static-web
spec:
  containers:
    - name: create-dir
      image: alpine
      command: ['sh', '-c', 'sleep 5 && echo "create dir" && mkdir -p /opt/log && echo test > /opt/log/test.txt && sleep infinity']
      volumeMounts:
        - name: data
          mountPath: /opt
    - name: app2
      image: alpine
      command: ['sh', '-c', 'echo " app is runnign" && cat /opt/log/test.txt && sleep infinity']
      volumeMounts:
        - name: data
          mountPath: /opt
  volumes:
    - name: data
      emptyDir: {}