apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-readpod1
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["watch", "list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bindin-reader
  namespace: default
subjects:
- kind: User
  name: a.prisyazhnyuk
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-readpod1
  apiGroup: rbac.authorization.k8s.io