apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user
subjects:
- kind: User #Group #User
  name: user #ops   #test
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: user
  apiGroup: rbac.authorization.k8s.io