apiVersion: v1
kind: ConfigMap
metadata:
  name: mymap
  # namespace: ingress-nginx
data:
  port: "8080"
  default.conf: |
      server {
      listen 80;
      server_name mysite.com;

      location / {
        root /usr/share/nginx/html;
        }
      }
  index.html: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>My Website Home Page</title>
      </head>
      <body>

        <p>My name is Alexey Prisyazhnyuk and this is my web page </p>
      </body>
      </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  # namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnginx
  template:
    metadata:
      labels:
        app: webnginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: vol
      volumes:
      - name: vol
        configMap:
          name: mymap

---

apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  # namespace: ingress-nginx
spec:
  selector:
    app: webnginx
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80

---

  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: example
    # namespace: ingress-nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    ingressClassName: nginx
    rules:
      - host: example.com
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: nginxservice
                  port:
                    number: 80
              path: /
            - pathType: Prefix
              backend: 
                service:
                  name: nginxservice
                  port:
                    number: 9001
              path: /test
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
      - hosts:
        - www.example.com
        secretName: example-tls

---

  apiVersion: v1
  kind: Secret
  metadata:
    name: example-tls
    namespace: ingress-nginx
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREVENDQWZXZ0F3SUJBZ0lVTkl3OWpLYzQ5S2gxWEhta293d0REMkFpNXlBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZqRVVNQklHQTFVRUF3d0xaWGhoYlhCc1pTNWpiMjB3SGhjTk1qUXdNakl4TVRFeU9UTXpXaGNOTWpVdwpNakl3TVRFeU9UTXpXakFXTVJRd0VnWURWUVFEREF0bGVHRnRjR3hsTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNWjlaQ1lUNy9nc2pUK2x1MW1kVEdTVkVsN1RweFZiYXErZ1ZpdWoKZjZ2QVdONzdBaUc4am1BVnAxT1g0THBzVmNRUFpGMXVyKzVLWDF6S0hkcTVzeVRSZ25zdEd2OFd1dGgvZFVtcApOU3NiMVFyVVQ2WHNERjdHcHJjY1NHbXFZaXhNWUpKYlFNWVYyZWRWWm5jelpTMWQvV0dySkgzREwwWmZRMEp0CmFpbnhpZXpVVnVjZm53RlU4Ym1pWlh4NlBKMnZCZUZDMGJtcTNGblJVWitUWWhzNXdnVWpYaklqSzdLUkRJbkoKWDN3dEd1d1B2aDRmUmpLVDJsR3g0VndlczdSWHl5NkNBUnoxZ0M2QTZsTmthN204enhWUTAzZXlyUFBDK01LMwpzYW1pTXJpMnZKMzZSYXRQWktpdnNSbm1WT1NmeGZ5bEltTTYzWHhzYm9mZWJ0RUNBd0VBQWFOVE1GRXdIUVlEClZSME9CQllFRk5PS0M1dWIzOWc2cjRvbm1XVVE2RVZkV3BjM01COEdBMVVkSXdRWU1CYUFGTk9LQzV1YjM5ZzYKcjRvbm1XVVE2RVZkV3BjM01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQgpBRllLdml3eEFkald2dUN6SjdmelZMZGY2YkROVGF0TkZsc1llZHlreHRnQnAvQS9veEQyYVV3WVN0RVNOczNFCk5KUUhzaFZXSWtoWkFSYXh6Unh0Ulh0SHpDREoxRVdTVUJtdHRoVUlmdUdlT1c0TTlwajVheGExSis4b2V3R3QKSGpEWDN4S3hNV3J6dzJudSs0amJVR0tMa3lVdnYxaUgrbkV2VFhsUWxCTnFwZk9NTE9pOVBHTUQvclVMNFdaRgpqSnNNMytMQ044a2RodENWZFd0U3JITStBRzNpTyt2YlBkQ2hjeGdYOGFNYTZPMlhnd1p2V3FMMkZlMk1Vd2hvCnhBS2pQTERRWlhlSkhlZEdtWXQvVEpLSTNMWTViZEFlN0lITi8vdzNBcGhtdXNlMlIvTVN2M3pEdjd2SEZEWUgKOTFHdFV2dW1LbDZUY2diRnYweVFma0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRREdmV1FtRSsvNExJMC8KcGJ0Wm5VeGtsUkplMDZjVlcycXZvRllybzMrcndGamUrd0lodkk1Z0ZhZFRsK0M2YkZYRUQyUmRicS91U2w5Ywp5aDNhdWJNazBZSjdMUnIvRnJyWWYzVkpxVFVyRzlVSzFFK2w3QXhleHFhM0hFaHBxbUlzVEdDU1cwREdGZG5uClZXWjNNMlV0WGYxaHF5Ujl3eTlHWDBOQ2JXb3A4WW5zMUZibkg1OEJWUEc1b21WOGVqeWRyd1hoUXRHNXF0eFoKMFZHZmsySWJPY0lGSTE0eUl5dXlrUXlKeVY5OExScnNENzRlSDBZeWs5cFJzZUZjSHJPMFY4c3VnZ0VjOVlBdQpnT3BUWkd1NXZNOFZVTk4zc3F6end2akN0N0dwb2pLNHRyeWQra1dyVDJTb3I3RVo1bFRrbjhYOHBTSmpPdDE4CmJHNkgzbTdSQWdNQkFBRUNnZ0VCQUlheWJSWVNEWlVDMXMvTWJqbEFMNmxLS0c5RmZtdFY0QzVTeG1kU3lyOEoKQnNZNjNKVjhXYm9HdDhoWWx0NnJ5Z0FFMmYwMXNob3BTbEd6cjFMUkZpcjBLbkhnaUNOM2oxQ0FIbDNnZi81RApJdTM0YWh5VTlVZ1QwdXNNUEcvSWVsckpjZmVnQ1hMalBUNXBpK0YwZFVLMk44N2h6eCt4SnhIQWIrcFNTZXN2CmxqVExCZ2FyWUg3UzIrbExvcGtacm9HUTcxdVRjU2N0TlF6ZU1mL1RBZysxeVhWalVKVVV5ZS9ocm1iN0RRNVkKL3IyS2NBRE9hMk9sUFFtVGNIWlpwOC9oY2xBZVRsWUVraWJBbHZJNU16eTRXVGhYQ3Zqc01JdU94a21obnVKRQpWb1REdWFqanpBNlZVMU45dEdZYWI1TlZPa3I3OG1XUUpLZFI4d0VaT21FQ2dZRUE3S1k1Q1gwMWxjcVRaQ2F0CmRuL2gybnJkd1JzOG5lWEdxaUJyenNXS09ZUElldWd5bG5iY1d2c2ZKQklodS9kc2ZWM2FIK0VvZThFQ0xMVXUKTkFZV202TUxua00xdVNCaVJvTG5SWDVvSDNjS3NVNnB2b0tPdWpqQ0ErMTBQRHRQKzVsQmMzMmNIRGZYdy9mNApLNkI4TFdrNWJFSjU5UHZCOHhQU1NZcFhScTBDZ1lFQTFyaGdSaDNkK2RJYmU3UzhrZGo4WjZTckhJWC8zZEMvCkZ6RmFqdE1Oc2ZEenE5K3pzaVRFa2Y1VUlyRnFXTWlzeVBGRU1nUFRhWWhIZ0ExbTA3SkhnN3ZTbXA5dGxYT0oKMTN4RXhzL04zRFlhaUp0SXZmNVg5c2pHd3lxZDF0TjJLZkpJUlJybkQ2OHBrQ0YvVkl4RVgyQXorWUY5OUdYYgpoSVFVSUo4Q29UVUNnWUVBeHlyNnRBN0tLNEJyM2cxalRtbEF0M1ZTN3pReUp4Mzh2ckE4cTdDN3JiNUkyNUJUCkN5bU1PWkpDV2tSY1dldGFSb1RYa0o4YVNGVmZ0Q3JrY09weTJwZzFyZ1FZMGU3OFp5WEM2VTBDNndCd1lsdTMKSnR5UXJSQVowZDVtUms4UStNcTZPQzRPVmYxMXZid1VCUHV6cHpCNUlMRXVIVTVKcElBWktzV2d3SjBDZ1lFQQpneDhpdzQ2M29EaGJTaWJyeEpEaVNoUjMzYnBDcnQwcjVHamlLVGZmTkJ1MVllOEEyRGUxeG9XdU1XVndVUGx5CjhsN0xTMU9reGR4UDlYVzVwbXRIV3IzVzlVK0ladXlnYjNQV3VDWHNTNTdLZzBONG4zVnptQ094cFRzZ0dqRVcKQnJXS3hwQ1FLN2JHeGRwKzNFMnY3eUpiZXZGRnpucHBIRHBmNUMvV05rVUNnWUFUYjQ4Z0RIWVprWURyZ2dMegpENGllSmhOdlQvY1NrVGlnQW50WkZsanRhaFIvK2k2Y2hrd2JzcmEyMDJnRVhPOXFBckdGWWpqM1FwS2o1RUVOCjJkZ081VFdXSForYm1JckllLzE0MGM5UGlpQ2UwcjBXN0U4U2RGWFdqMlZhWUdUeGxvRXBjYWRVNHFBRmZydTIKZHBiSzlETDlWalliVzBiNExWd0l5NFpTUWc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
  type: kubernetes.io/tls