apiVersion: v1
kind: ConfigMap
metadata:
  name: mymap
data:
  port: "8080"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-dir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dir
  template:
    metadata:
      labels:
        app: dir
    spec:
      containers:
      - image: nginx
        name: nginx

      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: mymap
                key: port